### PR TITLE
Several cleanups to "ring.h".

### LINKED ISSUE #75: add include guards (or pragma once) to ring and inplace_function headers

### LINKED ISSUE #77: Build fails (on gcc 5.4)
... due to something in the ring buffer:

``` c++
In file included from /home/carlcook/workspace/sg14/SG14/SG14_test/SG14_test.cpp:6:0:
/home/carlcook/workspace/sg14/SG14/cmake/../SG14/ring.h:119:44: error: friend declaration ‘sg14::ring_iterator< <template-parameter-1-1>, <anonymous> >::type& sg14::operator+=(sg14::ring_iterator< <template-parameter-1-1>, <anonymous> >::type&, int)’ declares a non-template function [-Werror=non-template-friend]
   friend type& operator+=(type& it, int i) noexcept;
                                            ^
compilation terminated due to -Wfatal-errors.
```

### PR DESCRIPTION
**Pull request by Quuxplusone**
- Add `#pragma once`.
- Add a non-member ADL swap() for rings.
- Fix up the namespace of operator+= and operator-= for ring iterators.
- Fix up (it + n) and (it - n) for ring iterators.
- Add (it - it) for ring iterators.
- Fix a typo in (a >= b) for ring iterators, and make (a <= b) == !(b > a).
- Add the implicit conversion from iterator to const_iterator.
- `#if 0` the broken tests for unimplemented static_ring and dynamic_ring.

Fixes #75, #77, #90, #93, #101.

Ping @hatcat, @TBBle.

### CODE REVIEW

**Comment by martinmoene** [comment]
1. I'm not sure sg14::swap() should be here. std::swap() suffices (closed issue #98).
2. Perhaps include a fix for issue #91 (default popper); proposal also needs this fix.
3. Perhaps include a fix for issue #101 (ring_iterator::operator>=()).

**Comment by Quuxplusone** [comment]
1. I tend to think that everything ever should have an ADL non-member `swap`. You're right that this custom ADL `swap` isn't really any more performant than `std::swap` in this case.

2. Perhaps. I'll investigate.

3. Yikes. I'm happy to add that to this PR, or separately.

**Comment by Quuxplusone** [comment]
3. added to this PR. I'd like to defer the rest of those issues to a different PR, just to get this one merged. (I don't have merge permissions for this repo.)

File: SG14/ring.h [hunk 1]
```diff
@@ -364,21 +387,21 @@ template <typename Ring, bool is_const>
...
-	return (m_idx <= rhs.m_idx) && (m_rv == rhs.m_rv);
+	return !(rhs < *this);
 }
 
 template <typename Ring, bool is_const>
 template<bool C>
 bool sg14::ring_iterator<Ring, is_const>::operator>(const sg14::ring_iterator<Ring, C>& rhs) const noexcept
 {
-	return (m_idx > rhs.m_idx) && (m_rv == rhs.m_rv);
+	return (rhs > *this);
```
Comment (martinmoene) [inline SG14/ring.h]: s/`>`/`<`/

Comment (Quuxplusone) [inline SG14/ring.h]: Yikes!  The fix and a regression test are now in 5013c6c.
