### PR TITLE
Fix behavior of ring_span's copy_popper<T>, and general popper cleanup.

### LINKED ISSUE #91: Fix return of ring_span's copy_popper<T>::operator()
in:
```
template <typename T>
T sg14::copy_popper<T>::operator()(T& t)
{
	T old = t;
	t = copy;
	return t;
}
```
shouldn't `return t` be **`return old`**?

### LINKED ISSUE #102: Add missing copy_popper(T const&) ctor for ring_span
Missing from both proposal and reference code.

### PR DESCRIPTION
**Pull request by Quuxplusone**
Fixes #91. Apparently the typo `t` for `old` is also in the current
paper http://wg21.link/p0059r3 — we should fix that too!

Fixes #102.

### CODE REVIEW

File: SG14/ring.h [hunk 1]
```diff
@@ -157,26 +158,27 @@ namespace sg14
...
-T sg14::copy_popper<T>::operator()(T& t)
+T sg14::copy_popper<T>::operator()(T& t) const
 {
-	T old = t;
-	t = copy;
-	return t;
+	T old = m_copy;
+	using std::swap;
+	swap(old, t);
+	return old;
```
Comment (Quuxplusone) [inline SG14/ring.h]: This dance makes the operation exception-safe, in case that matters. If copying `m_copy` into `old` throws an exception, then the swap doesn't happen and the value of `t` is preserved.

File: SG14/ring.h [hunk 2]
```diff
@@ -10,21 +10,22 @@ namespace sg14
...
+		T operator()(T& t) const;
 	};
 
 	template <typename T>
 	struct copy_popper
 	{
-		copy_popper(T&& t);
-		T operator()(T& t);
-		T copy;
+		explicit copy_popper(T t);
```
Comment (Quuxplusone) [inline SG14/ring.h]: Notice that I'm changing this from `T&&` to just `T`, which fixes #102 in an elegant way. I don't think there's any downside to this change.

Comment (TBBle) [inline SG14/ring.h]: The `explicit` broke one of the tests included here: https://github.com/WG21-SG14/SG14/commit/aba97661a03d99712d87bba61c1d4fd03569eb05#commitcomment-22430301
